logging:
  path: /var/log/
  file: Bodyshop.log
  level: 
    root: warn
    org.springframework.security: info
    
greetings:
  welcome: Hello my little bro from ${spring.application.name}

bodyshop:
  orders:
    pageSize: 15
    
spring:
  artemis:
    host: 0.0.0.0
    port: 61616
    user: admin
    password: admin