logging:
  path: /var/logs/
  file: Bodyshop.log
  level: 
    root: warn
    org.springframework.security: info
    
greetings:
  welcome: Hello my little bro from ${spring.application.name}

bodyshop:
  orders:
    pageSize: 15
    